export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";

export const USER_UPDATE_STATUS_REQUEST = "USER_UPDATE_STATUS_REQUEST";
export const USER_UPDATE_STATUS_SUCCESS = "USER_UPDATE_STATUS_SUCCESS";
export const USER_UPDATE_STATUS_FAIL = "USER_UPDATE_STATUS_FAIL";

